# Docker-compose for Graylog

rabbit1:
  image: "rabbitmq:3.6.11-alpine"
  hostname: "rabbit1"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    - "./definitions.json:/etc/rabbitmq/definitions.json:ro"
